# action.yml
name: 'Query recent issues'
description: 'Query recent issues and construct summary email body'
inputs:
  repo_name:  # id of input
    description: 'Repository containing issues to report'
    required: true
    default: 'geneontology/go-ontology'
  duration_in_days:
    description: 'Number of days to look back for new or updated issues'
    required: true
    default: 1
outputs:
  issue_email_body:
    description: 'Body of issue list email to send'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo_name }}
    - ${{ inputs.duration_in_days }}
