on: [push]

jobs:
  query_recent_issues:
    runs-on: ubuntu-latest
    name: A job to query for recent issues
    steps:
    # To use this repository's private action,
    # you must check out the repository
    - name: Checkout
      uses: actions/checkout@v2
    - name: Query recent issues
      id: issue_query
      uses: ./ # Uses an action in the root directory
      with:
        repo_name: ${{ github.repository }}
        duration_in_days: 1
#    # Use the output from the `issue_query` step
#    - name: Get the issue list email body
#      run: |
#        wc <<< $issue_email_body
#        echo "${{ steps.issue_query.outputs.issue_email_body }}"
